- name: installing nginx using playbook
  hosts: nodes #Group of node
  become: yes #for root access
  tasks: #tasks/Collection/modules to run
    - name: install nginx
      ansible.builtin.apt: 
        name: nginx
        stete: installed
    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started