- name: using variables.yaml file to access variables
  hosts: nodes
  vars_files:
  - variables.yaml
  tasks:
    - name: my info
      ansible.builtin.debug:
      msg: "Hello, My name is {{NAME}}\nI am pursuing {{COURSE}} at the age of{{AGE}}"