- name: using variables.yaml file to access variables
  hosts: nodes
  vars_files: # to tell yaml file to use variables.yaml for accessing variables
  - variables.yaml
  tasks:
    - name: my info
      ansible.builtin.debug:
        msg: "Hello, My name is {{NAME}}. I am pursuing {{COURSE}} at the age of {{AGE}}"