# using variables from cli 
# to give variable we will use -e 

- name: Getting Variables from command line
  hosts: localhost
  tasks:
    - name: printing variables
      ansible.builtin.debug:
        msg: "how much are your headphones worth: {{PRICE}}"


# Command to run: 
#   ansible-playbook -i inventory -e ansible_user=<USERNAME> -e ansible_password=<PASSWORD> -e PRICE=1000 08-vars-arges.yaml