- name: creating ansible playbook to check user
  hosts: localhost
  tasks:
    - name: cmd command to work with ansible
      ansible.builtin.command: id roboshop
      register: output # {{output}} is the variable name  
      ignore_errors: True
    - name: print output
      ansible.builtin.debug:
       msg: "{{output}}"
    - name: only printing output status
      ansible.builtin.debug:
        msg: "{{output.rc}}"
    - name: create/adduser roboshop if not exist
      ansible.builtin.user:
        name: roboshop
      when: output.rc != 0
