- name: simple condition
  hosts: localhost
  vars:
    NAME: Sarthak
  tasks:
    - name: print Only if NAME==Sarthak
      ansible.builtin.debug:
        msg: "Hello {{NAME}}"
      when: NAME == "Sarthak" #if this expression is true module will run
    - name: print Only if NAME==DevOps
      ansible.builtin.debug:
        msg: "Hello {{NAME}}" #this will not get printed due to the condition
      when: NAME == "DevOps" 