- name: using loops in ansible
  hosts: localhost
  
  tasks:
    - name: print items using loops
      ansible.builtin.debug:
        loop:
        - ramesh
        - rakesh
        - raman
        - rajesh
        msg: "Hello {{item}}"