- name: using loops in ansible
  hosts: localhost
  
  tasks:
    - name: print items using loops
      ansible.builtin.debug:
        msg: "Hello {{loop}}"
      loop:
        - ramesh
        - rakesh
        - raman
        - rajesh