- name: advanced package installer using loop
  hosts: nodes
  become: yes
  tasks: 
    - name: using map inside list of loop
      ansible.builtin.apt:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
      - {name: 'nginx' ,state: 'absent'}
      - {name: 'postfix' ,state: 'present'}
      - {name: 'mailx' ,state: 'absent'}
      - {name: 'net-tools' ,state: 'present'}
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
    - name: get output of playbook
      ansible.builtin.command: systemctl status nginx
      register: output
    - name: print output
      ansible.builtin.debug:
        msg: "{{output}}" 
    