- name: advanced package installer using loop
  hosts: nodes
  become: yes
  tasks: 
    - name: using map inside list of loop
      ansible.builtin.apt:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
      - {name: 'nginx' ,state: 'absent'}
      - {name: 'postfix' ,state: 'present'}
      - {name: 'mailx' ,state: 'absent'}
      - {name: 'net-tools' ,state: 'present'}